### PR TITLE
Fix build with GHC 8.10

### LINKED ISSUE #10: 1.0.1.4 (downloaded via cabal) does not build?
The current version (1.0.1.4) does not seem to build. 1.0.1.3 and older work fine. This is the build log:
```
Failed to build splint-1.0.1.4.
Build log (
/home/xyz/.cabal/logs/ghc-8.10.5/splint-1.0.1.4-52e524397f720e3a35d891e7c76c9c128e94ea5b6cc919e77742b116cb049411.log
):
Configuring library for splint-1.0.1.4..
Preprocessing library for splint-1.0.1.4..
Building library for splint-1.0.1.4..
[1 of 5] Compiling Splint.GHC.Bag   ( src/ghc-8.10/Splint/GHC/Bag.hs, dist/build/Splint/GHC/Bag.o, dist/build/Splint/GHC/Bag.dyn_o )
[2 of 5] Compiling Splint.GHC.Error ( src/ghc-8.10/Splint/GHC/Error.hs, dist/build/Splint/GHC/Error.o, dist/build/Splint/GHC/Error.dyn_o )
[3 of 5] Compiling Splint.GHC.Plugins ( src/ghc-8.10/Splint/GHC/Plugins.hs, dist/build/Splint/GHC/Plugins.o, dist/build/Splint/GHC/Plugins.dyn_o )
[4 of 5] Compiling Splint.Parser    ( src/ghc-8.10/Splint/Parser.hs, dist/build/Splint/Parser.o, dist/build/Splint/Parser.dyn_o )

src/ghc-8.10/Splint/Parser.hs:15:31: error:
    • Couldn't match type ‘([Data.Map.Internal.Map](http://data.map.internal.map/)
                              ApiAnnotation.ApiAnnKey [GHC.SrcSpan],
                            [Data.Map.Internal.Map](http://data.map.internal.map/)
                              GHC.SrcSpan [GHC.Located ApiAnnotation.AnnotationComment])’
                     with ‘ghc-lib-parser-9.0.2.20211226:GHC.Parser.Annotation.ApiAnns’
      Expected type: ghc-lib-parser-9.0.2.20211226:GHC.Parser.Annotation.ApiAnns
        Actual type: ApiAnnotation.ApiAnns
    • In the first argument of ‘HLint.createModuleEx’, namely ‘apiAnns’
      In the second argument of ‘($)’, namely
        ‘HLint.createModuleEx apiAnns hsModule’
      In a stmt of a 'do' block:
        pure $ HLint.createModuleEx apiAnns hsModule
   |
15 |   pure $ HLint.createModuleEx apiAnns hsModule
   |                               ^^^^^^^

src/ghc-8.10/Splint/Parser.hs:15:39: error:
    • Couldn't match type ‘GHC.GenLocated
                             GHC.SrcSpan (GHC.Hs.HsModule GHC.Hs.Extension.GhcPs)’
                     with ‘ghc-lib-parser-9.0.2.20211226:GHC.Types.SrcLoc.GenLocated
                             ghc-lib-parser-9.0.2.20211226:GHC.Types.SrcLoc.SrcSpan
                             ghc-lib-parser-9.0.2.20211226:GHC.Hs.HsModule’
      NB: ‘ghc-lib-parser-9.0.2.20211226:GHC.Types.SrcLoc.GenLocated’
            is defined in ‘GHC.Types.SrcLoc’
                in package ‘ghc-lib-parser-9.0.2.20211226’
          ‘GHC.GenLocated’ is defined in ‘SrcLoc’ in package ‘ghc-8.10.5’
      Expected type: ghc-lib-parser-9.0.2.20211226:GHC.Types.SrcLoc.Located
                       ghc-lib-parser-9.0.2.20211226:GHC.Hs.HsModule
        Actual type: GHC.Located (GHC.Hs.HsModule GHC.Hs.Extension.GhcPs)
    • In the second argument of ‘HLint.createModuleEx’, namely
        ‘hsModule’
      In the second argument of ‘($)’, namely
        ‘HLint.createModuleEx apiAnns hsModule’
      In a stmt of a 'do' block:
        pure $ HLint.createModuleEx apiAnns hsModule
   |
15 |   pure $ HLint.createModuleEx apiAnns hsModule
   |                                       ^^^^^^^^
cabal: Failed to build splint-1.0.1.4 (which is required by
test:l4re-model-test from l4re-model-0.1.0.0 and exe:l4re-model from
l4re-model-0.1.0.0). See the build log above for details.
```

### PR DESCRIPTION
**Pull request by tfausak**
This will fix #10. 

I'm not sure what the problem is yet. But it turns out that I wasn't actually building anything in CI. I was used to Stack's CLI, which builds things when you run `stack test` even if there are no tests. Cabal's CLI is different because if you run `cabal test` without any tests, it doesn't build anything. So with any luck I should see this fail in CI shortly.

### CODE REVIEW

**Comment by tfausak** [comment]
I think GHC 8.10 might be a bit of a red herring. Really this problem happens because `hlint-3.3.x` switched to `ghc-lib-parser-9.0.x`. 

One way to fix this would be to support arbitrary versions of GHC and HLint at the same time, which is what Splint currently does. However HLint seems to have move to an approach where version X uses `ghc-lib-parser` version Y. So if I want to support, say, HLint 3.4 on GHC 8.10, I have to consume `ghc-lib-parser-9.2.x`'s output and use it as input for `ghc-8.10.x`. Frankly I'm not interested in supporting that matrix. 

A simpler solution is to pin a major version of HLint and then allow multiple versions of GHC. I suspect that's a much more common use case anyway.

**Comment by tfausak** [comment]
What I _want_ to be able to say is: "If `hlint`'s version of `ghc-lib-parser` matches the version of `ghc`, then use a 'native' parser. Otherwise use a 'fallback' parser." Unfortunately Cabal's conditionals aren't expressive enough for that. I think I can do that with CPP (that's how I did things before #8), but I'm not sure if it's worth the trouble.
